apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ems
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: aadus/ems-backend:v1
        ports:
        - containerPort: 8080
        env:
        # ✅ MySQL configs from ConfigMap
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: ems-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: ems-config
              key: MYSQL_PORT
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: ems-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: ems-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_PASSWORD

        # ✅ Mongo URI from ConfigMap
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: ems-config
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ems
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
